# Generated by Django 4.2.1 on 2025-05-19 07:15

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ficheiro', models.FileField(upload_to='documents/', validators=[users.models.validate_pdf])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.perfil')),
            ],
        ),
    ]
