# Generated by Django 4.2.1 on 2025-05-19 08:22

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_monografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='monografia',
            name='resumo',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monografia',
            name='ficheiro',
            field=models.FileField(upload_to='monografias/', validators=[users.models.validate_pdf]),
        ),
    ]
