# Generated by Django 4.2.1 on 2025-05-19 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_monografia_resumo_alter_monografia_ficheiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='resumo',
            field=models.TextField(),
        ),
    ]
