# Generated by Django 4.2.1 on 2025-05-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_monografia_date_alter_monografia_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='monografia',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='monografias/capas/'),
        ),
    ]
