# Generated by Django 4.2.1 on 2025-05-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_monografia_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monografias', to='users.perfil'),
        ),
    ]
