# Generated by Django 4.2.1 on 2025-05-20 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_monografia_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('ficheiro', models.FileField(upload_to='tese/', validators=[users.models.validate_pdf])),
                ('capa', models.ImageField(blank=True, null=True, upload_to='tese/capas/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tese', to='users.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('ficheiro', models.FileField(upload_to='livro/', validators=[users.models.validate_pdf])),
                ('capa', models.ImageField(blank=True, null=True, upload_to='livro/capas/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro', to='users.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Dissertacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('ficheiro', models.FileField(upload_to='dissertação/', validators=[users.models.validate_pdf])),
                ('capa', models.ImageField(blank=True, null=True, upload_to='dissertação/capas/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissertação', to='users.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('ficheiro', models.FileField(upload_to='artigo/', validators=[users.models.validate_pdf])),
                ('capa', models.ImageField(blank=True, null=True, upload_to='artigo/capas/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigo', to='users.perfil')),
            ],
        ),
    ]
