# Generated by Django 4.2.1 on 2025-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tese_livro_dissertacao_artigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='faculdade',
            field=models.CharField(choices=[('no', 'empty'), ('eng', 'Faculdade de Engenharia'), ('dir', 'Faculdade de Direito'), ('ges', 'Faculdade de Gestão'), ('econ', 'Faculdade de Economia')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='dissertacao',
            name='faculdade',
            field=models.CharField(choices=[('no', 'empty'), ('eng', 'Faculdade de Engenharia'), ('dir', 'Faculdade de Direito'), ('ges', 'Faculdade de Gestão'), ('econ', 'Faculdade de Economia')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='livro',
            name='faculdade',
            field=models.CharField(choices=[('no', 'empty'), ('eng', 'Faculdade de Engenharia'), ('dir', 'Faculdade de Direito'), ('ges', 'Faculdade de Gestão'), ('econ', 'Faculdade de Economia')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='monografia',
            name='faculdade',
            field=models.CharField(choices=[('no', 'empty'), ('eng', 'Faculdade de Engenharia'), ('dir', 'Faculdade de Direito'), ('ges', 'Faculdade de Gestão'), ('econ', 'Faculdade de Economia')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='tese',
            name='faculdade',
            field=models.CharField(choices=[('no', 'empty'), ('eng', 'Faculdade de Engenharia'), ('dir', 'Faculdade de Direito'), ('ges', 'Faculdade de Gestão'), ('econ', 'Faculdade de Economia')], default='no', max_length=20),
        ),
    ]
