# Generated by Django 4.2.1 on 2025-05-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_dissertacao_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertacao',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissertacoes', to='users.perfil'),
        ),
    ]
