# Generated by Django 4.2.1 on 2025-05-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monografia',
        ),
    ]
